name: feed_example
description: Example app using likemind's feed UI+SDK packages

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.5.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  feed_sx:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true