name: feed_sx
description: Flutter sample UI package for LikeMinds Feed SDK
version: 0.6.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  chewie: ^1.3.6
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  fluttericon: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  path: ^1.8.2
  path_provider: ^2.0.11
  url_launcher: ^6.1.7
  video_player: ^2.4.10
  timeago: 
  likeminds_feed: 0.6.0
  image_picker: ^0.8.6+1
  collection: ^1.16.0
  lazy_load_scrollview: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  flutter_notification_channel: ^2.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  overlay_support: 2.1.0
  envied: ^0.3.0
  get_it: ^7.2.0
  photo_view: ^0.14.0
  extended_text_field: ^11.0.0

  flutter_typeahead: 
    path: lib/src/packages/flutter_typeahead-4.3.7
  

  # likeminds_feed: 
  #   path: ../LikeMinds-Flutter-SDK


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  

flutter:


  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/feed_sx/assets/images/avatar.png
    - packages/feed_sx/assets/images/avatar2.png
    - packages/feed_sx/assets/images/post.png
    - packages/feed_sx/assets/images/hamburger.png
    - packages/feed_sx/assets/icons/like.svg
    - packages/feed_sx/assets/icons/comment.svg
    - packages/feed_sx/assets/icons/bookmark.svg
    - packages/feed_sx/assets/icons/share.svg
    - packages/feed_sx/assets/icons/doc_pdf.svg
    - packages/feed_sx/assets/icons/cross.svg
    - packages/feed_sx/assets/icons/add_photo.svg
    - packages/feed_sx/assets/icons/add_video.svg
    - packages/feed_sx/assets/icons/add_attachment.svg
    - packages/feed_sx/assets/icons/reply.svg
    - packages/feed_sx/assets/icons/like_filled.svg
    - packages/feed_sx/assets/icons/posts.svg
    - packages/feed_sx/assets/icons/new_post.svg
